# Generated by Django 4.2 on 2024-05-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_staffprofile_user_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "admin"),
                    ("staff", "staff"),
                    ("user", "user"),
                    ("company", "company"),
                ],
                default="user",
                max_length=20,
            ),
        ),
    ]
