# Generated by Django 4.2 on 2024-06-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_rental_user",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
