# Generated by Django 4.2 on 2024-05-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rental", "0002_customerdocument_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
