# Generated by Django 4.2 on 2024-05-30 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rental", "0004_customerproperty"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnconfirmInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("month_name", models.CharField(max_length=100)),
                ("property_rent", models.FloatField()),
                ("total_electricity_unit", models.FloatField()),
                ("total_electricity_amount", models.FloatField()),
                ("total_water_unit", models.FloatField()),
                ("total_water_amount", models.FloatField()),
                ("total_garbage_amount", models.FloatField()),
                ("miscellaneous_amount", models.FloatField()),
                ("total_price", models.FloatField()),
                ("remarks", models.TextField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rental.customer",
                    ),
                ),
                (
                    "myproperty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rental.property",
                        verbose_name="property",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("month_name", models.CharField(max_length=100)),
                ("property_rent", models.FloatField()),
                ("total_electricity_unit", models.FloatField()),
                ("total_electricity_amount", models.FloatField()),
                ("total_water_unit", models.FloatField()),
                ("total_water_amount", models.FloatField()),
                ("total_garbage_amount", models.FloatField()),
                ("miscellaneous_amount", models.FloatField()),
                ("total_price", models.FloatField()),
                ("remarks", models.TextField()),
                ("is_cancelled", models.FloatField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rental.customer",
                    ),
                ),
                (
                    "myproperty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rental.property",
                        verbose_name="property",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_date"],
                "abstract": False,
            },
        ),
    ]
