# Generated by Django 4.2 on 2024-06-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rental", "0008_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerproperty",
            name="electricity_unit_reading",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
