# Generated by Django 4.2 on 2024-06-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rental", "0009_customerproperty_electricity_unit_reading"),
    ]

    operations = [
        migrations.AddField(
            model_name="unconfirminvoice",
            name="electricity_unit_reading",
            field=models.FloatField(default=0),
        ),
    ]
