# Generated by Django 4.2 on 2024-06-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rental", "0011_invoice_electricity_unit_reading"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="electricity_unit_reading",
            new_name="current_electricity_unit_reading",
        ),
        migrations.RenameField(
            model_name="unconfirminvoice",
            old_name="electricity_unit_reading",
            new_name="current_electricity_unit_reading",
        ),
        migrations.AddField(
            model_name="invoice",
            name="last_electricity_unit_reading",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="unconfirminvoice",
            name="last_electricity_unit_reading",
            field=models.FloatField(default=0),
        ),
    ]
