# Generated by Django 4.2 on 2024-05-07 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_unconfirmuserplan_alter_userplan_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unconfirmuserplan',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='unconfirmuserplan',
            name='starting_date',
        ),
    ]
