# Generated by Django 4.2 on 2024-05-07 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_remove_unconfirmuserplan_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unconfirmuserplandetail',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='unconfirmuserplandetail',
            unique_together={('userplan', 'plan')},
        ),
    ]
