# Generated by Django 4.2 on 2024-05-08 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_staffprofile'),
        ('plan', '0005_alter_unconfirmuserplandetail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unconfirmuserplan',
            name='starting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unconfirmuserplandetail',
            name='userplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unconfirmuserplan', to='plan.unconfirmuserplan'),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userplan', to='accounts.userprofile'),
        ),
    ]
