# Generated by Django 4.2 on 2024-05-08 04:46

from django.db import migrations, models
import plan.models.userplan


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_unconfirmuserplan_starting_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unconfirmuserplan',
            name='starting_date',
            field=models.DateField(blank=True, default=plan.models.userplan.get_tomorrow, null=True),
        ),
    ]
