# Generated by Django 4.2 on 2024-05-08 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_staffprofile'),
        ('plan', '0007_alter_unconfirmuserplan_starting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unconfirmuserplan',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unconfirmuserplan', to='accounts.userprofile'),
        ),
    ]
