# Generated by Django 4.2 on 2024-05-08 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_alter_unconfirmuserplan_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unconfirmuserplandetail',
            name='userplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unconfirmuserplandetails', to='plan.unconfirmuserplan'),
        ),
        migrations.AlterField(
            model_name='userplandetail',
            name='userplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userplandetails', to='plan.userplan'),
        ),
    ]
