# Generated by Django 4.2 on 2024-05-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0009_alter_unconfirmuserplandetail_userplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='discount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userplan',
            name='total',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
