# Generated by Django 4.2 on 2024-05-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0010_userplan_discount_userplan_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplan',
            name='end_date',
        ),
        migrations.AddField(
            model_name='userplan',
            name='plan_price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
