# Generated by Django 4.2 on 2024-05-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0011_remove_userplan_end_date_userplan_plan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='ending_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
