# Generated by Django 4.2 on 2024-05-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0012_userplan_ending_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
